name: 📖 Build and Deploy Book

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  QUARTO_VERSION: "1.4.550"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: ${{ env.QUARTO_VERSION }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-latex-recommended

      - name: Validate Quarto files
        run: |
          echo "Checking required files..."
          for file in index.qmd navegacion.qmd archivos.qmd busqueda.qmd desarrollo.qmd multimedia.qmd red.qmd monitoreo.qmd texto.qmd utilidades.qmd; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing: $file"
              exit 1
            fi
          done
          echo "✅ All required files found"

      - name: Build Quarto book
        run: |
          quarto render --to html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_book

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
